rework, everything tested

diff --git a/git_aliases b/git_aliases
--- a/git_aliases
+++ b/git_aliases
@@ -17,57 +17,101 @@
 
 [alias]
   #get/set integration branch
-  intbr       = "!f() { [ $# -eq 0 ] && { git config 4f.intbr && exit $? || exit $? ;}; \
-                        [ $# -eq 1 ] &&                                                 \
-                          {                                                             \
-                            $( git show-ref --quiet --verify -- \"refs/heads/$1\" ) &&  \
-                                { git config 4f.intbr $1 && exit $? || exit $? ;}   ||  \
-                                { echo Not a valid branch refs/heads/$1 >&2 && exit 1 ;};   \
-                          };                                                            \
-                        [ $# -gt 1 ] && { echo Too many parameters >&2 && exit 1 ;};        \
+  intbr       = "!f() { [ $# -eq 0 ] &&                                                   \
+                          {                                                               \
+                            git config 4f.intbr &&                                        \
+                                exit 0 ||                                                 \
+                                { echo \"Integration branch not set\" >&2 && exit 1 ;};   \
+                          };                                                              \
+                        [ $# -eq 1 ] &&                                                   \
+                          {                                                               \
+                            $( git show-ref --quiet --verify -- \"refs/heads/$1\" ) &&    \
+                                { git config 4f.intbr $1 && exit $? || exit $? ;}   ||    \
+                                { echo Not a valid branch refs/heads/$1 >&2 && exit 1 ;}; \
+                          };                                                              \
+                        [ $# -gt 1 ] && { echo Too many parameters >&2 && exit 2 ;};      \
                       }; f"
+  intbr-unset = config --unset 4f.intbr
+  intbr-istracked = "!f() { br_int=$(git intbr) || exit 1; \
+                            u=$(git rev-parse --symbolic-full-name --abbrev-ref $br_int@{upstream} 2>/dev/null) && \
+                            { echo \"$br_int <- $u\" && exit 0 ;} || \
+                            { echo Integration branch \\'$br_int\\' not tracked >&2 && exit 1 ;} ; \
+                          }; f"
 
   #switch aliases
-  chk-intbr     = "!git intbr 2>1 1>/dev/null && git checkout $(git intbr)"
+  chk-intbr   = "!git intbr 1>/dev/null && git checkout $(git intbr)"
   chk-back    = checkout @{-1}
 
+  currbr      = "!f() { currbr=$(git symbolic-ref -q HEAD) || { echo 'detahced-head' && exit 1 ;}; \
+                        currbr=$(git rev-parse --symbolic-full-name --abbrev-ref $currbr);         \
+                        echo $currbr;                                                              \
+                      }; f"
+
   #feature branch mgt
-  ftrbr-start = "!f() { [ $# -ne 1 ] && echo \"Missing br name\" >&2 && exit 1; \
-                         br_int=$(git intbr) || { echo \"Integration branch not set\" >&2 && exit 1 ;}; \
-                         br_ftr_pre=$(git config --get 4f.ftrbr-prefix) 2>/dev/null; \
-                         git checkout $br_int             && \
-                         echo \"Pulling $(git intbr)\"    && \
-                         git pull                         && \
-                         echo \"Creating new ftr branch\" && \
-                         git checkout -b ${br_ftr_pre}$1 \
+  ftrbr-start = "!f() { [ $# -ne 1 ] && echo \"Usage: git ftrbr-start <brname>\" >&2 && exit 2; \
+                         br_int=$(git intbr) || exit 1;                                         \
+                         br_ftr_pre=$(git config --get 4f.ftrbr-prefix) 2>/dev/null;            \
+                         git chk-intbr || exit 1 &&                                             \
+                         { discardoutput=$(git intbr-istracked 2>&1) &&                         \
+                             { echo Pulling \\'$(git intbr)\\' && git pull ;} ||                \
+                             { echo Intbr \\'$(git intbr)\\' not tracked, jump pull. ;} ;       \
+                         }                                                             &&       \
+                         echo Creating new ftr branch starting from \\'$(git intbr)\\' &&       \
+                         git checkout -b ${br_ftr_pre}$1                                        \
                        ;}; f"
 
-  ftrbr-sidepull = !git intbr 2>1 1>/dev/null || (echo Integration branch not set >&2 && exit 1) && \
-                     git chk-intbr   && \
-                     git pull     && \
-                     git chk-back  && \
-                     echo Merging $(git intbr) into current branch && \
-                     git merge $(git config --get 4f.ftrbr-pull-merge-opt) $(git intbr)
+  ftrbr-integrate = "!f() { br_start=$(git currbr) || { echo Cannot exec from detached-head >&2 && exit 1 ;}; \
+                            git chk-intbr || exit 1;                                         \
+                            { discardoutput=$(git intbr-istracked 2>&1) &&                   \
+                                { echo Pulling \\'$(git intbr)\\' && git pull || exit 1;} || \
+                                { echo Intbr \\'$(git intbr)\\' not tracked, jump pull. ;} ; \
+                            }                                                             && \
+                            echo Merging \\'$br_start\\' into \\'$(git intbr)\\' &&          \
+                            git merge $(git config --get 4f.ftrbr-push-merge-opt) $br_start; \
+                          }; f"
 
-  ftrbr-integrate = "!f() { br_start=$(git symbolic-ref -q HEAD) || { echo Cannot exec from detached-head >&2 && exit 1 ;}; \
-                             git intbr 2>1 1>/dev/null           || { echo Integration branch not set >&2 && exit 1 ;}; \
-                             git chk-intbr                            && \
-                             echo \"Pulling $(git intbr)\"            && \
-                             git pull                                 && \
-                             echo Merging $br_start into $(git intbr) && \
-                             git merge $(git config --get 4f.ftrbr-push-merge-opt) $br_start \
-                            ;}; f"
+  ftrbr-integrate-rebase   = "!f() { br_start=$(git currbr)  || { echo Cannot exec from detached-head >&2 && exit 1 ;}; \
+                                     git ftrbr-update-rebase || exit 1;                                \
+                                     git chk-intbr           || exit 1;                                \
+                                     echo Merging \\'$br_start\\' into \\'$(git intbr)\\';             \
+                                     git merge $(git config --get 4f.ftrbr-push-merge-opt) $br_start;  \
+                             }; f"
+                              
+  ftrbr-update-merge = "!f() { br_start=$(git currbr) || { echo Cannot exec from detached-head >&2 && exit 1 ;}; \
+                               br_int=$(git intbr)    || exit 1;                                                 \
+                               { discardoutput=$(git intbr-istracked 2>&1)                                       \
+                                   && { git chk-intbr && echo Pulling \\'$(git intbr)\\' && git pull && git checkout $br_start || exit 1 ;} \
+                                   || { echo Intbr \\'$(git intbr)\\' not tracked, jump pull. ;} ;               \
+                               }                                                                &&               \
+                               echo Merging \\'$(git intbr)\\' into \\'$br_start\\'              &&              \
+                               git merge $(git config --get 4f.ftrbr-push-merge-opt) $(git intbr);               \
+                             }; f"
 
-  ftrbr-sidepush = !git ftrbr-integrate && echo \"Pushing $(git intbr) onto origin\" && git push origin $(git intbr)
+  ftrbr-update-rebase   = "!f() { br_start=$(git currbr) || { echo Cannot exec from detached-head >&2 && exit 1 ;}; \
+                                  br_int=$(git intbr) || exit 1;                                                    \
+                                  { discardoutput=$(git intbr-istracked 2>&1)                                       \
+                                      && { git chk-intbr && echo Pulling \\'$(git intbr)\\' && git pull && git checkout $br_start || exit 1 ;} \
+                                      || { echo Intbr \\'$(git intbr)\\' not tracked, jump pull. ;} ;               \
+                                  }                                                                &&               \
+                                  echo Rebasing \\'$br_start\\' onto \\'$(git intbr)\\'            &&               \
+                                  git rebase $(git intbr) ;                                                         \
+                                }; f"
 
-  ftrbr-done     = !git ftrbr-sidepush && git branch -d $(git rev-parse --symbolic-full-name --abbrev-ref @{-1})
+  ftrbr-push = "!f() { br_int=$(git intbr)                         || exit 1; \
+                       discardoutput=$(git intbr-istracked 2>&1)   || { echo Intbr \\'$(git intbr)\\' not tracked, cannot push. >&2 && exit 1 ;}; \
+                       remote=$(git config --get branch.$(git intbr).remote); \
+                       git ftrbr-integrate                         || exit 1; \
+                       echo Pushing \\'$(git intbr)\\' to \\'$remote\\';      \
+                       git push $remote $(git intbr);                         \
+                     }; f"
 
-  ftrbr-rebase   = !git chk-intbr                                                   && \
-                    git pull                                                        && \
-                    git chk-back                                                    && \
-                    echo \"Rebasing $(git symbolic-ref -q HEAD) onto $(git intbr)\" && \
-                    git rebase $(git intbr)
-
+  ftrbr-push-rebase = "!f() { br_int=$(git intbr)                         || exit 1; \
+                              discardoutput=$(git intbr-istracked 2>&1)   || { echo Intbr \\'$(git intbr)\\' not tracked, cannot push. >&2 && exit 1 ;}; \
+                              remote=$(git config --get branch.$(git intbr).remote); \
+                              git ftrbr-integrate-rebase                  || exit 1; \
+                              echo Pushing \\'$(git intbr)\\' to \\'$remote\\';      \
+                              git push $remote $(git intbr);                         \
+                            }; f"
 
 #configurations
 #[4f]
